"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$camel\
$swift\
$bun\
$aws\
$terraform\
$buf\
$c\
$conda\
$dart\
$docker_context\
$elixir\
$elm\
$haskell\
$haxe\
$java\
$julia\
$lua\
$python\
$rlang\
$ruby\
$scala \
$package \
[ ](fg:#1d2230)\
\n$shell\
$character"""

right_format = """
[](fg:#1d2230)\
$status\
[$git_state](bg:#a3aed2 fg:#a3aed2)\
[$git_status](bg:#a3aed2 fg:#a3aed2)\
[](fg:#769ff0 bg:#212736)\
$username\
$hostname\
[](bg:#769ff0 fg:#a3aed2)\
[ ](bg:#a3aed2 fg:#a3aed2)
[$cmd_duration $time $battery](bg:#1d2230 fg:#a3aed2)\
[▓▒░](#a3aed2)\
"""

continuation_prompt = '▶▶ '

scan_timeout = 10

[character]
success_symbol = '[λ](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = "[❮](bold green)"

[status]
style = "fg:red bg:#1d2230"
format = '[$status ]($style)'
disabled = false

[username]
format = "[$user]($style)"
style_user = "fg:#e3e5e5 bg:#769ff0"
style_root = "fg:#ff0000 bg:#769ff0"
show_always = true

[hostname]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[@$hostname ]($style)"
trim_at = "-"
ssh_only = false
disabled = false

[shell]
fish_indicator = ''
powershell_indicator = 'PS:'
unknown_indicator = '?:'
nu_indicator = 'nu:'
bash_indicator = '$:'
cmd_indicator = 'cmd:'
style = 'green bold'
disabled = false

[cmd_duration]
min_time = 500
format = "[[ ⌛ $duration](fg:yellow bg:#1d2230)]($style)"

[time]
disabled = false
time_format = "%R"                                     # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time](fg:#a0a9cb bg:#1d2230)]($style)'

[battery]
disabled = false
full_symbol = ""
charging_symbol = " "
discharging_symbol = " "
unknown_symbol = ""
empty_symbol = ""
format = "[$symbol$percentage ]($style)"
[[battery.display]]
threshold = 10
style = "fg:#a0a9cb bg:#1d2230"
[[battery.display]]
threshold = 20
style = "bg:#DE935F fg:#111111"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = "🔒"
read_only_style = "red"

[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Movies" = ""
"Sources" = ""
"~" = ""
"/" = "  "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
format = "[ $tag ]($style)"
style = "bold green"

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "fg:#769ff0 bg:#1d2230"
conflicted = "="
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count} "
stashed = "$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
disabled = false

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[hg_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[bun]
symbol = '  '
style = "bg:#212736"
#detect_files = ["package.json"]
#detect_folders = ["node_modules"]
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[swift]
symbol = " "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[perl]
symbol = " "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[aws]
# disabled = true
symbol = " "
style = "bg:#e4c180"
format = '[[](bg:#e4c180 fg:#A6A6A6)$symbol$profile(\($region\))[](bg:#A6A6A6 fg:#e4c180)]($style)'

[terraform]
symbol = " "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[cmake]
# disabled = true
# symbol = "卑" # alternate
symbol = "喝"
style = "bg:#57686B fg:#EEEEEE"
format = "[[](bg:#57686B fg:#A6A6A6)$symbol$version[](bg:#A6A6A6 fg:#57686B)]($style)"

[buf]
symbol = "  "

[c]
symbol = "  "

[conda]
disabled = false
symbol = " "
style = "bg:#a4b595 fg:#111111"
ignore_base = true
truncation_length = 1
format = "[[](bg:#a4b595 fg:#A6A6A6)$symbol$environment[](bg:#A6A6A6 fg:#a4b595)]($style)"

[crystal]
# disabled = true
symbol = " "
style = "bg:#EEEEEE fg:#111111"
format = "[[](bg:#EEEEEE fg:#A6A6A6)$symbol$version[](bg:#A6A6A6 fg:#EEEEEE)]($style)"

[dart]
# disabled = true
symbol = " " # original
# symbol = "﯑ " # clearer
style = "bg:#32BBF9 fg:#111111"
format = "[[](bg:#32BBF9 fg:#A6A6A6)$symbol$version[](bg:#A6A6A6 fg:#32BBF9)]($style)"

[docker_context]
symbol = "  "
format = "[$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = "  "

[elm]
symbol = "  "

[haskell]
symbol = "  "

[haxe]
symbol = " ⌘ "

[java]
symbol = "  "

[julia]
symbol = "  "

[lua]
symbol = "  "

[memory_usage]
symbol = "  "

[nim]
symbol = "  "

[python]
symbol = "  "
#pyenv_version_name = true
format = '[${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[rlang]
symbol = " ﳒ "

[ruby]
symbol = "  "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[scala]
symbol = "  "

[os]
format = "[$symbol]($style)"
style = "fg:#769ff0 bg:#1d2230"
disabled = false

[os.symbols]
Alpaquita = "  "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = "  "
Artix = "  "
CentOS = "  "
Debian = "  "
DragonFly = "  "
Emscripten = "  "
EndeavourOS = "  "
Fedora = "  "
FreeBSD = "  "
Garuda = " ﯑ "
Gentoo = "  "
HardenedBSD = " ﲊ "
Illumos = "  "
Linux = "  "
Mabox = "  "
Macos = "  "
Manjaro = "  "
Mariner = "  "
MidnightBSD = "  "
Mint = "  "
NetBSD = "  "
NixOS = "  "
OpenBSD = "  "
openSUSE = "  "
OracleLinux = "  "
Pop = "  "
Raspbian = "  "
Redhat = "  "
RedHatEnterprise = "  "
Redox = "  "
Solus = " ﴱ "
SUSE = "  "
Ubuntu = "  "
Unknown = "  "
Windows = "  "

[package]
symbol = " "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false
