name:
  .bunfig.toml: 
  .cargo: 
  .dockerignore: 
  .emacs.d: 
  .git: 
  .gitattributes: 
  .gitignore: 
  .trash: 
  a.out: 
  bun.lockb: 
  bunfig.toml: 
  Dockerfile: 
  package-lock.json: 
  package.json: 
  pnpm-lock.yaml: 
  pnpm-workspace.yaml: 
  poetry.lock: 
  poetry.toml: ﯑
  pyproject.toml: 
  tsconfig.json: 
  yarn.lock: 
extension:
  "c++": 
  "f#": 
  7z: 
  ai: 
  bat: 
  bmp: 
  bz: 
  bz2: 
  c: 
  cc: 
  cjs: 
  clj: 
  cljc: 
  cljs: 
  coffee: 
  conf: 
  cp: 
  cpp: 
  css: 
  cxx: 
  d: 
  dart: 
  db: 
  diff: 
  dump: 
  edn: 
  ejs: 
  erl: 
  fish: 
  fs: 
  fsi: 
  fsscript: 
  fsx: 
  gif: 
  go: 
  gz: 
  hbs: 
  hrl: 
  hs: 
  htm: 
  html: 
  ico: 
  ini: 
  java: 
  jl: 
  jpeg: 
  jpg: 
  js: 
  json: 
  jsx: 
  less: 
  lhs: 
  lock: 
  log: 
  lua: 
  markdown: 
  md: 
  mdx: 
  mjs: 
  ml: λ
  mli: λ
  mustache: 
  php: 
  pl: 
  pm: 
  png: 
  psb: 
  psd: 
  py: 
  pyc: 
  pyd: 
  pyo: 
  rb: 
  rlib: 
  rs: 
  rss: 
  scala: 
  scss: 
  sh: 
  slim: 
  sln: 
  sql: 
  styl: 
  suo: 
  t: 
  tar: 
  toml: 󰅪
  ts: 
  tsx: 
  twig: 
  txt: 
  vim: 
  xul: 
  xz: 
  yaml: 
  yml: 
  zip: 
filetype:
  device-block: 
  device-char: 
  dir: 
  executable: 
  file: 
  pipe: 
  socket: 
  special: 
  symlink-dir: 
  symlink-file: 
